[package]
name = "parquet-to-commitments"
edition.workspace = true
exclude.workspace = true
repository.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
proof-of-sql.workspace = true
rand.workspace = true
rand_chacha.workspace = true

[lints]
workspace = true
