[package]
name = "proofs"
version = "0.0.0" # This version will be automatically updated
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "24.0.0"
pedersen = {version = "3.0", registry = "pedersen_reg"}
bumpalo = { version = "3.11.0", features = ["collections"] }
byte-slice-cast = "1.2.1"
integer-encoding = "3.0.4"
ark-ff = { git = "https://github.com/arkworks-rs/algebra.git", rev = "bf1e24211df2be1ee317e382aa128281766e9c1f" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra.git", rev = "bf1e24211df2be1ee317e382aa128281766e9c1f" }
ark-std = "^0.3.0"
curve25519-dalek = { version = "3", features = ["serde"] }
hashbrown = "0.11.2"
merlin = "2"
thiserror = "1"
serde = { version = "1", features = ["serde_derive"] }
postcard = {version = "1.0", features = ["alloc"] }
num-traits = "0.2"
rayon = "1.5"

[dev_dependencies]
rand = "0.7"
rand_core = "0.5"
criterion = "0.4"

[[bench]]
name = "sumcheck"
harness = false
