[package]
name = "provable_sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
clap = { version = "4", features = ["derive"] }

# SxT dependencies
proofs = { path = "../../crates/proofs", features = ["test"] }
proofs-sql = { path = "../../crates/proofs-sql" }

[build-dependencies]
cc = { version = "1.0", optional = true }

[features]
default = []
valgrind = ["dep:cc"]
